### ISSUE TITLE
@tybys/wz 安装失败

### ISSUE THREAD

**Issue by ximan** [toyobayashi/wz#5]
你好，我尝试了最新版、旧版nodejs，install始终报错。

目前用的是nodejs v10.20.1，执行npm install @tybys/wz，下载失败，mapledemo\node_modules\@tybys 下面没有wz文件夹

![image](https://github.com/toyobayashi/wz/assets/2944289/54db81f1-6f7c-4fa1-8517-74b56e840e6c)

请问是需要安装Python吗？我不做开发，只是想使用代码提取音乐、图片等素材。

**Comment by toyobayashi** [comment]
如果只是想提取的话，用 https://github.com/lastbattle/Harepacker-resurrected 这个就好了。
你安装失败的原因是，这个项目包含了 https://github.com/toyobayashi/windows-file-version-info 这个 C 写的 node 包，所以本地 npm install 的时候需要编译 C 代码，编译过程需要用到 node-gyp 构建系统，它是python写的。

**Comment by ximan** [comment]
谢谢耐心解答。写轮眼只能编辑、导出一个，我想批量导出全部资源，所以才找到您这个项目的。

我还是想尝试一下您B站视频这个批量下载过程（https://www.bilibili.com/video/BV1AA411E7zB/ ），请问我还需要做什么操作呢？理论上这些操作应该也需要写到咱们这个项目的readme上吧，否则其他小白或许也会遇到类似我这种疑问。

**Comment by toyobayashi** [comment]
首先你要安装好 python 确保 `python.exe` 的安装目录在 `%Path%` 环境变量中

然后要安装 MSVC（微软家的C/C++编译工具链，会比较麻烦），这一步二选一

- 安装 [Microsoft Visual Studio 2022](https://visualstudio.microsoft.com/zh-hans/downloads/)，社区版的就行，勾选 【使用C++的桌面开发】后安装，或者
- 安装 [Microsoft C++ 生成工具](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)，勾选 【使用C++的桌面开发】后安装

重启电脑后 Node.js C++ 模块的编译环境就准备好了，保持【良好的网络环境】重新 `npm install`，不出意外的话依赖可以安装成功。

我不能保证在这里留下简单的几句话可以确保你流畅地把流程跑通，而且项目很久没有跟进 Harepacker 的实现，存在已经不支持最新版的 maplestory 文件的可能。

**Comment by ximan** [comment]
收到，非常感谢！
